s=input("enter a string:")
print("length of ",s,"is",len(s))
print(" string in lower case is",s.lower())
print("string in upper case is",s.upper())
print("changing of case of string is ",s.swapcase())
print(" 1 st letter of string in upper case is",s.capitalize())
print("string with first letter of all word is capitalized is ",s.title())
m=input("enter a string with + charecter:")
print("left side copy of+ will be removed",m.lstrip('+'))
print("right side copy of+ will be removed",m.rstrip('+'))
print("perform both lstrip and rstrip",m.strip('+'))
print("return maximum alphabetical charecter from string",max(s))
print("return minimum alphabetical charecter from string",min(s))
